eureka:
  client:
    serviceUrl:
      defaultZone: http://chensen:123456@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
