eureka:
  client:
    serviceUrl:
      defaultZone: http://chensen:123456@localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}  
  
